In [23]:
import os
import pydicom
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Specify the path to your DICOM folder
#dicom_folder_path = 'D:\\script_di_ale\\dicoms\\2122818'  # Notice the double backslashes for Windows paths
dicom_folder_path = r"D:\script_di_ale\dicoms"
excel_path = r"D:\script_di_ale\I3LUNG_CT_series_number.xlsx"
df = pd.read_excel(excel_path)

#show lines where CT_series_number is 5,6 or 7 and SEG_series_number is '1001', '1004', '1975', '1052', '1054'
df2 = df[(df['CT_series_number'].isin([9,14]))]
df2 = df2[(df2['SEG_series_number'].isin([1001, 1027]))]
dicom_folder_path += '\\' + df2['I3LUNG_ID'].iloc[0]
print(dicom_folder_path)
# List to hold all the DICOM datasets
dicom_datasets = {}
print(os.listdir(dicom_folder_path))
# Loop through all the files in the folder
try:
        os.remove(os.path.join(dicom_folder_path, 'desktop.ini'))
        print("tolto lo stronzo")
        
except:
        print('ah... t\'appost')
    
for filename in os.listdir(dicom_folder_path):
    file_path = os.path.join(dicom_folder_path, filename)
    # Read the DICOM file
    ds = pydicom.dcmread(file_path)
    # Append the dataset to the list
    dicom_datasets[filename] = ds


D:\script_di_ale\dicoms\INT1010671
['03LDCT.CT._.1021.22.2021.10.23.12.23.00.254.77918131.dcm', '03LDCT.CT._.1021.23.2021.10.23.12.23.00.254.77918142.dcm', '03LDCT.CT._.1021.24.2021.10.23.12.23.00.254.77918153.dcm', '03LDCT.CT._.11.1.2021.10.23.12.23.00.254.77914435.dcm', '03LDCT.CT._.11.10.2021.10.23.12.23.00.254.77914534.dcm', '03LDCT.CT._.11.100.2021.10.23.12.23.00.254.77915524.dcm', '03LDCT.CT._.11.101.2021.10.23.12.23.00.254.77915535.dcm', '03LDCT.CT._.11.102.2021.10.23.12.23.00.254.77915546.dcm', '03LDCT.CT._.11.103.2021.10.23.12.23.00.254.77915557.dcm', '03LDCT.CT._.11.104.2021.10.23.12.23.00.254.77915568.dcm', '03LDCT.CT._.11.105.2021.10.23.12.23.00.254.77915579.dcm', '03LDCT.CT._.11.106.2021.10.23.12.23.00.254.77915590.dcm', '03LDCT.CT._.11.107.2021.10.23.12.23.00.254.77915601.dcm', '03LDCT.CT._.11.108.2021.10.23.12.23.00.254.77915612.dcm', '03LDCT.CT._.11.109.2021.10.23.12.23.00.254.77915623.dcm', '03LDCT.CT._.11.11.2021.10.23.12.23.00.254.77914545.dcm', '03LDCT.CT._.11.110.2

In [24]:
#keep filenames with series number 9
dicom_files = [name for name in dicom_datasets.keys() if dicom_datasets[name].SeriesNumber == 9]
dicom_files.sort()
dicom_files

['03LDCT.CT._.9.1.2021.10.23.12.23.00.254.77911663.dcm',
 '03LDCT.CT._.9.10.2021.10.23.12.23.00.254.77911762.dcm',
 '03LDCT.CT._.9.100.2021.10.23.12.23.00.254.77912752.dcm',
 '03LDCT.CT._.9.101.2021.10.23.12.23.00.254.77912763.dcm',
 '03LDCT.CT._.9.102.2021.10.23.12.23.00.254.77912774.dcm',
 '03LDCT.CT._.9.103.2021.10.23.12.23.00.254.77912785.dcm',
 '03LDCT.CT._.9.104.2021.10.23.12.23.00.254.77912796.dcm',
 '03LDCT.CT._.9.105.2021.10.23.12.23.00.254.77912807.dcm',
 '03LDCT.CT._.9.106.2021.10.23.12.23.00.254.77912818.dcm',
 '03LDCT.CT._.9.107.2021.10.23.12.23.00.254.77912829.dcm',
 '03LDCT.CT._.9.108.2021.10.23.12.23.00.254.77912840.dcm',
 '03LDCT.CT._.9.109.2021.10.23.12.23.00.254.77912851.dcm',
 '03LDCT.CT._.9.11.2021.10.23.12.23.00.254.77911773.dcm',
 '03LDCT.CT._.9.110.2021.10.23.12.23.00.254.77912862.dcm',
 '03LDCT.CT._.9.111.2021.10.23.12.23.00.254.77912873.dcm',
 '03LDCT.CT._.9.112.2021.10.23.12.23.00.254.77912884.dcm',
 '03LDCT.CT._.9.113.2021.10.23.12.23.00.254.77912895.dcm',
 

In [ ]:
"""for ds in dicom_datasets:
    # Access patient information
    patient_name = ds.get('PatientName', 'Unknown')  # Default to 'Unknown' if PatientName is not present
    patient_id = ds.get('PatientID', 'Unknown')
    series = ds.get('SeriesNumber', 'Unknown')
    convolution_kernel = ds.get('ConvolutionKernel', 'Unknown')
    # Access imaging parameters
    modality = ds.get('Modality', 'Unknown')
    study_date = ds.get('StudyDate', 'Unknown')
    
    print(f"Patient Name: {patient_name}, Patient ID: {patient_id}, Modality: {modality}, Study Date: {study_date}")
    print(f"Series: {series}, Convolution Kernel: {convolution_kernel}")
    print("*" * 25)
"""

'for ds in dicom_datasets:\n    # Access patient information\n    patient_name = ds.get(\'PatientName\', \'Unknown\')  # Default to \'Unknown\' if PatientName is not present\n    patient_id = ds.get(\'PatientID\', \'Unknown\')\n    series = ds.get(\'SeriesNumber\', \'Unknown\')\n    convolution_kernel = ds.get(\'ConvolutionKernel\', \'Unknown\')\n    # Access imaging parameters\n    modality = ds.get(\'Modality\', \'Unknown\')\n    study_date = ds.get(\'StudyDate\', \'Unknown\')\n    \n    print(f"Patient Name: {patient_name}, Patient ID: {patient_id}, Modality: {modality}, Study Date: {study_date}")\n    print(f"Series: {series}, Convolution Kernel: {convolution_kernel}")\n    print("*" * 25)\n'

In [ ]:
import os
import tempfile
import shutil
import dicom2nifti
import nibabel as nib
#dicom_files is files with series 9


# Create a temporary directory
temp_dir_dicom = tempfile.mkdtemp()
temp_dir_out = tempfile.mkdtemp()
nifti_output_path = r"D:\script_di_ale"

# Copy the DICOM files to the temporary directory
for file_path in dicom_files:
    file_path = os.path.join(dicom_folder_path, file_path)
    shutil.copy(file_path, temp_dir_dicom)

# Specify the NIfTI file output path in the current working directory


# Convert the DICOM files in the temporary directory to a NIfTI file
dicom2nifti.convert_directory(temp_dir_dicom, temp_dir_out, compression=True, reorient=True)
#take the file in temp out and rename it
for filename in os.listdir(temp_dir_out):
    file_path = os.path.join(temp_dir_out, filename)
    shutil.copy(file_path, nifti_output_path)
    os.rename(nifti_output_path + '\\' + filename, nifti_output_path + '\\' + "fighissimo.nii.gz")



# Load the NIfTI file and inspect the affine matrix and other details
nifti_img = nib.load(nifti_output_path + '\\' + "fighissimo.nii.gz")
print("Affine matrix:")
print(nifti_img.affine)

# Display additional information as needed, e.g., image shape
print("Image shape:", nifti_img.shape)

# Clean up: Remove the temporary directory and its contents when done
shutil.rmtree(temp_dir_dicom)
shutil.rmtree(temp_dir_out)


Affine matrix:
[[-7.40234375e-01  0.00000000e+00  0.00000000e+00  1.93129883e+02]
 [-0.00000000e+00  7.40234375e-01  0.00000000e+00 -3.51298828e+01]
 [ 0.00000000e+00 -0.00000000e+00  3.00000000e+00 -7.78900024e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Image shape: (512, 512, 240)


In [26]:
import subprocess
import logging

os.sep = "/"
volume, pseudonym = "D:" + os.sep + "script_di_ale", os.sep + "tmp" + os.sep + "script_di_ale"
output_labels = pseudonym + os.sep + "output"
def run_docker_command(input_path, name, format="nifti"):
    # Corrected Docker command with volume mapping and paths adjusted for Windows
    command = [
        "docker", "run", 
        "-v", f"{volume}:{pseudonym}", 
        "qiicr/dcmqi", 
        "segimage2itkimage", 
        "-t", format,
        "-p", name,
        "--outputDirectory", output_labels, 
        "--inputDICOM", input_path
    ]

    # Run the command
    print("should be running")
    print(f"Running Docker command: {' '.join(command)}")
    result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    if result.returncode == 0:

        logging.info("Docker command executed successfully!")
        logging.info(f"Output:\n{result.stdout}")
    else:
        logging.error("Error running Docker command:")
        logging.error(f"Error output:\n{result.stderr}")



In [27]:
#dicom_files is files with series 1027
dicom_files = [name for name, key in dicom_datasets.items() if key.SeriesNumber == 1027][0]

dicom_files

'03LDCT.SEG._.1027.1.2021.10.23.12.23.00.254.77911630.dcm'

In [34]:
input_path = os.path.join(dicom_folder_path, dicom_files)
input_path = input_path.replace("\\","/")
input_path = input_path.replace("D:", "/tmp")
print(input_path)
run_docker_command(input_path, "belizimo")

/tmp/script_di_ale/dicoms/INT1010671/03LDCT.SEG._.1027.1.2021.10.23.12.23.00.254.77911630.dcm
should be running
Running Docker command: docker run -v D:/script_di_ale:/tmp/script_di_ale qiicr/dcmqi segimage2itkimage -t nifti -p belizimo --outputDirectory /tmp/script_di_ale/output --inputDICOM /tmp/script_di_ale/dicoms/INT1010671/03LDCT.SEG._.1027.1.2021.10.23.12.23.00.254.77911630.dcm


In [ ]:
#print first of dicom_files to check if it is the right one
print(dicom_datasets[dicom_files[2]])

Dataset.file_meta -------------------------------
(0002, 0000) File Meta Information Group Length  UL: 198
(0002, 0001) File Meta Information Version       OB: b'\x00\x01'
(0002, 0002) Media Storage SOP Class UID         UI: Segmentation Storage
(0002, 0003) Media Storage SOP Instance UID      UI: 1.3.12.2.1107.5.8.15.132076.30000021091516110119800003090
(0002, 0010) Transfer Syntax UID                 UI: Explicit VR Little Endian
(0002, 0012) Implementation Class UID            UI: 1.3.12.2.1107.5.99.3.20080101
(0002, 0013) Implementation Version Name         SH: 'SIEMENS'
-------------------------------------------------
(0008, 0005) Specific Character Set              CS: 'ISO_IR 100'
(0008, 0008) Image Type                          CS: ['DERIVED', 'PRIMARY']
(0008, 0012) Instance Creation Date              DA: '20210915'
(0008, 0013) Instance Creation Time              TM: '164235'
(0008, 0016) SOP Class UID                       UI: Segmentation Storage
(0008, 0018) SOP Instance 

In [ ]:
def find_first_difference(str1, str2):
    # Iterate over the shorter of the two strings
    for index in range(min(len(str1), len(str2))):
        # Check if characters at the current position are different
        if str1[index] != str2[index]:
            # Return the index of the first difference
            return index
    # If no difference has been found within the length of the shorter string,
    # and the strings are of different lengths, return the length of the shorter string.
    # Otherwise, return None as the strings are identical.
    if len(str1) != len(str2):
        return min(len(str1), len(str2))
    return None  # The strings are identical

# Example usage
index = find_first_difference("hello", "helicopter")
print(index)  # This will print the index of the first differing character

3


In [ ]:
#compare all lines taht are not (0008, 1115) with the series 1027 if there is some difference, print the lines
for ds in dicom_datasets:
    if dicom_datasets[ds].SeriesNumber == 1027:
        #get every line that is not (0008, 1115)
        for line in dicom_datasets[ds]:
            if line.tag != (0x0008, 0x1115):
                #compare with last file
                if dicom_datasets[ds][line.tag] != dicom_datasets[dicom_files[2]][line.tag]:
                    #convert to string to compare
                    line0 = str(dicom_datasets[ds][line.tag])
                    line1 = str(dicom_datasets[dicom_files[1]][line.tag])
                    line2 = str(dicom_datasets[dicom_files[2]][line.tag])
                    #print index of the first character that is different
                    print(line.tag)
                    print(line0)
                    print(line1)
                    print(line2)
                    print(' ' * find_first_difference(line0, line2) + '^' if find_first_difference(line0, line2) is not None else 'nuffin')
                    

                    print("*" * 25)
        

NameError: name 'dicom_datasets' is not defined

In [ ]:


#set stdout as logging
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')
#put all the files in a temporary folder normal folder in volume
temp_dir_dicom_path = volume + os.sep + "temp_dicom"
os.makedirs(temp_dir_dicom_path, exist_ok=True)
print(temp_dir_dicom_path)
for file_path in dicom_files:
    file_path = os.path.join(dicom_folder_path, file_path)
    print(file_path)
    shutil.copy(file_path, temp_dir_dicom_path)

#run the docker command
path = pseudonym + "/dicoms/3901792/DICOM/21091515/43190000"
run_docker_command(path, "segmentation")



D:/script_di_ale/temp_dicom
D:\script_di_ale\dicoms\3901792\DICOM\21091515\43190000\86059461
D:\script_di_ale\dicoms\3901792\DICOM\21091515\43190000\86059472
D:\script_di_ale\dicoms\3901792\DICOM\21091515\43190000\86059483
should be running
Running Docker command: docker run -v D:/script_di_ale:/tmp/script_di_ale qiicr/dcmqi segimage2itkimage -t nifti -p segmentation --outputDirectory /tmp/script_di_ale/output --inputDICOM /tmp/script_di_ale/dicoms/3901792/DICOM/21091515/43190000


ERROR:root:Error running Docker command:
ERROR:root:Error output:
Condition failed: I/O suspension or premature end of stream in /work/apps/seg/segimage2itkimage.cxx:41
terminate called after throwing an instance of 'int'
/dcmqi/docker_entry.sh: line 3:     7 Aborted                 $1 "${@:2}"



In [ ]:
7864320 / (512 * 512)

30.0